<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log Out_w-4 text-gray-dark d-none d-_876ee2</name>
   <tag></tag>
   <elementGuidId>8a28b4cf-b571-4f6f-b4db-b01758ffccea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.w-4.text-gray-dark.d-none.d-md-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0fa968ea-7d87-46cf-ac02-42ff754b9412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 text-gray-dark d-none d-md-block</value>
      <webElementGuid>17c620ef-141f-49d0-9e3d-110c1dacb983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b847b530-642f-4f01-b3c5-cd70bf711075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;flex-grow-1 h-full&quot;]/nav[@class=&quot;d-flex shadow-sm p-3 justify-content-between&quot;]/form[@class=&quot;d-sm-flex justify-content-start border align-items-center border-primary p-2 input-search&quot;]/button[@class=&quot;w-4 text-gray-dark d-none d-md-block&quot;]</value>
      <webElementGuid>90e24a25-fc72-4408-b3cd-c75df5f0e895</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>2cf9fafc-97da-4772-b6db-110ec175c832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/nav/form/button</value>
      <webElementGuid>45982c02-91b4-4e8e-afd0-75b21dd9f9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::button[1]</value>
      <webElementGuid>3b840300-0c65-4d1c-bf04-4865e5580d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payments'])[1]/following::button[1]</value>
      <webElementGuid>a80e59fe-e2a8-4c5c-9e1d-73a402cd8aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin111'])[1]/preceding::button[1]</value>
      <webElementGuid>75056cf2-a6b7-4510-9874-679ba2ee42e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Super admin'])[1]/preceding::button[1]</value>
      <webElementGuid>f228fc33-d9b6-4afd-90d5-05e239b08ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>76b41431-a271-40f9-a36a-a326542bd8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit']</value>
      <webElementGuid>3b51bf70-c033-43ac-bff6-baf79ca4fdb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
