<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log Out_search</name>
   <tag></tag>
   <elementGuidId>876c61b3-50fb-40e9-9076-6d46a4633d95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='g']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e19ab8df-0329-435c-ae45-9a8e93e499c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>1deb0107-8bc4-40d7-813e-5af16c91bf06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b2e0af0e-18a7-4cf4-90ef-eff67bc39fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>3f33f1e4-fd76-470a-be96-075b9629bce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>e7d5f2f7-cfb8-47e1-93dd-8e60dd59dacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>g</value>
      <webElementGuid>9efc46da-0400-46c7-aa9d-7289ba610d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;flex-grow-1 h-full&quot;]/nav[@class=&quot;d-flex shadow-sm p-3 justify-content-between&quot;]/form[@class=&quot;d-sm-flex justify-content-start border align-items-center border-primary p-2 input-search&quot;]/input[@class=&quot;search&quot;]</value>
      <webElementGuid>be7a1b82-47c2-403d-8127-abf59e1b72f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='g']</value>
      <webElementGuid>7fc76868-2ca1-480a-9a38-187891e00b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/nav/form/input</value>
      <webElementGuid>33336415-1f63-42cb-af05-684708a1394c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fc407b2f-7eed-4d95-9e74-204176777d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search']</value>
      <webElementGuid>5cd5d6c8-5a89-4e88-bd65-eece62925c02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
